const Nav = React.createClass({
    render: function() {
        return <nav>
                <ul>
                    <li><a href="/home">Home</a></li>
                    <li><a href="/home/about">About</a></li>
                    <li><a href="/home/contact">Contact</a></li>
                </ul>
                <p>This menu is server-side generated by React</p>
            </nav>;
    }
});

module.exports = Nav;
